version: "3.9"

services:
  waha:
    image: devlikeapro/waha
    platform: linux/amd64
    container_name: waha
    ports:
      - "3000:3000"
    environment:
      - WHATSAPP_DEFAULT_ENGINE=GOWS # Add this line
      - GODEBUG=netdns=go # Force the Go DNS resolver
      # This maps the .env variables into the container
      - WHATSAPP_HOOK_URL=http://backend:8080/webhook
      - WAHA_API_KEY=${WAHA_API_KEY}
      - WAHA_DASHBOARD_USERNAME=${WAHA_DASHBOARD_USERNAME}
      - WAHA_DASHBOARD_PASSWORD=${WAHA_DASHBOARD_PASSWORD}
      - WHATSAPP_SWAGGER_USERNAME=${WHATSAPP_SWAGGER_USERNAME}
      - WHATSAPP_SWAGGER_PASSWORD=${WHATSAPP_SWAGGER_PASSWORD}
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - ./waha_data:/app/.sessions
    restart: always # This ensures the container starts back up if it crashes or the Mac reboots

  # backend:
  #   build: ./backend
  #   container_name: nemoris-backend
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - postgres
  #     - redis

  postgres:
    image: postgres:15
    container_name: nemoris-postgres
    environment:
      POSTGRES_USER: nemoris
      POSTGRES_PASSWORD: nemoris
      POSTGRES_DB: nemoris
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7
    container_name: nemoris-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    command: redis-server --appendonly yes
    restart: always
